name: pipeline
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.21.0
      uses: actions/setup-node@v1
      with:
        node-version: 12.21.0
    - name: install & test
      run: npm ci
    - name: serverless deploy
      uses: tegud/serverless-github-action@1.66.0
      with:
        command: deploy
        args: "--stage=dev"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
